name: build
on:
  workflow_dispatch:

jobs:
  build:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t registry.home.dynamis.bbrfkr.net/rails-tutorial .
    - run: docker tag registry.home.dynamis.bbrfkr.net/rails-tutorial registry.home.dynamis.bbrfkr.net/rails-tutorial:${{ github.sha }}
    - run: docker push registry.home.dynamis.bbrfkr.net/rails-tutorial
    - run: docker push registry.home.dynamis.bbrfkr.net/rails-tutorial:${{ github.sha }}
