name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t registry.home.dynamis.bbrfkr.net/rails-tutorial .
    - run: docker tag registry.home.dynamis.bbrfkr.net/rails-tutorial registry.home.dynamis.bbrfkr.net/rails-tutorial:${{ github.sha }}
    - run: docker push registry.home.dynamis.bbrfkr.net/rails-tutorial
    - run: docker push registry.home.dynamis.bbrfkr.net/rails-tutorial:${{ github.sha }}
  change_image_tag:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v3
      with:
        repository: bbrfkr/rails-tutorial-manifests
        ref: master
        path: rails-tutorial-manifests
    - run: apt-get update && apt-get install -y jq jsonnet curl
    - run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        && sudo apt update
        && sudo apt install gh -y
    - run: cd rails-tutorial-manifests
    - run: |
        cat manifests/rails-tutorial.jsonnet |
        jsonnet params.libsonnet |
        jq '.image|="registry.home.dynamis.bbrfkr.net/rails-tutorial:${{ github.sha }}"' |
        jsonnet > manifests/rails-tutorial.jsonnet
    - run: |
        git diff --exit-code ||
        git config user.name github-actions[bot] &&
        git config user.email github-actions[bot]@users.noreply.github.com &&
        git add . &&
        git checkout -b from-rails-tutorial-${{ github.sha }} &&
        git push origin from-rails-tutorial-${{ github.sha }} &&
        gh pr create --base master --head from-rails-tutorial-${{ github.sha }} --title "from rails-tutorial: sha=${{ github.sha }}" --body ""
    - run:       